# Generated by Django 4.2.9 on 2024-01-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_desc', models.TextField()),
                ('product_category_id', models.PositiveIntegerField()),
                ('product_specification', models.TextField()),
                ('product_actual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_actual_cost_currency', models.CharField(max_length=3)),
                ('product_status', models.CharField(max_length=20)),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('category_id', models.PositiveIntegerField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('pwd_enc', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
