# Generated by Django 4.2.9 on 2024-01-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myappuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pwd_enc',
            new_name='password',
        ),
        migrations.DeleteModel(
            name='MyappUser',
        ),
    ]
